import { DaoProposal } from "types"

export const INITIAL_DAO_PROPOSAL: DaoProposal = {
  _isErc20: true,
  _isErc721: false,
  _isCustomVoting: false,
  _isDistributionProposal: false,
  _isValidator: false,
  _avatarUrl: "",
  _daoName: "",
  _websiteUrl: "",
  _description: "",
  _socialLinks: [],
  _documents: [{ name: "", url: "" }],
  _userKeeperParams: {
    tokenAddress: "",
    nftAddress: "",
    totalPowerInTokens: 0,
    nftsTotalSupply: 0,
  },
  _validatorsParams: {
    name: "",
    symbol: "",
    duration: 0,
    quorum: 0,
    validators: [""],
    balances: [0],
  },
  _internalProposalForm: {
    earlyCompletion: false,
    delegatedVotingAllowed: false,
    validatorsVote: true,
    duration: 0,
    durationValidators: 0,
    quorum: "0",
    quorumValidators: "0",
    minVotesForVoting: "0",
    minVotesForCreating: "0",
    rewardToken: "",
    creationReward: "0",
    executionReward: "0",
    voteRewardsCoefficient: "0",
    executorDescription: "internal",
  },
  _distributionProposalSettingsForm: {
    earlyCompletion: false,
    delegatedVotingAllowed: false,
    validatorsVote: true,
    duration: 0,
    durationValidators: 0,
    quorum: "0",
    quorumValidators: "0",
    minVotesForVoting: "0",
    minVotesForCreating: "0",
    rewardToken: "",
    creationReward: "0",
    executionReward: "0",
    voteRewardsCoefficient: "0",
    executorDescription: "DP",
  },
  _validatorsBalancesSettingsForm: {
    earlyCompletion: false,
    delegatedVotingAllowed: false,
    validatorsVote: true,
    duration: 0,
    durationValidators: 0,
    quorum: "0",
    quorumValidators: "0",
    minVotesForVoting: "0",
    minVotesForCreating: "0",
    rewardToken: "",
    creationReward: "0",
    executionReward: "0",
    voteRewardsCoefficient: "0",
    executorDescription: "validators",
  },
  _defaultProposalSettingForm: {
    earlyCompletion: false,
    delegatedVotingAllowed: false,
    validatorsVote: true,
    duration: 0,
    durationValidators: 0,
    quorum: "0",
    quorumValidators: "0",
    minVotesForVoting: "0",
    minVotesForCreating: "0",
    rewardToken: "",
    creationReward: "0",
    executionReward: "0",
    voteRewardsCoefficient: "0",
    executorDescription: "default",
  },
}
