export enum ICON_NAMES {
  angleLeft = "angle-left",
  angleRight = "angle-right",
  angleDown = "angle-down",
  angleUp = "angle-up",
  arrowDownFilled = "angle-down-filled",
  arrowUpFilled = "angle-up-filled",
  close = "close",
  dollarOutline = "dollar-outline",
  globe = "globe",
  shieldCheck = "shield-check",
  star = "star",
  fileDock = "file-dock",
  users = "users",
  angleLeftOutlined = "angle-left-outlined",
  angleRightOutlined = "angle-right-outlined",
  externalLink = "external-link",
  chatOutline = "chat-outline",
  copy = "copy",
  greenCheck = "green-check",
  trash = "trash",
  cog = "cog",
}
