export { default as DaoProfileTabAbout } from "./DaoProfileTabAbout"
export { default as DaoProfileTabBalance } from "./DaoProfileTabBalance"
export { default as DaoProfileTabValidators } from "./DaoProfileTabValidators"
export { default as DaoProfileTabDelegations } from "./DaoProfileTabDelegations"
export { default as TabFallback } from "./TabFallback"
